### ISSUE TITLE
RuntimeError: No valid build json!

### ISSUE THREAD

**Issue by maxamillion** [containerbuildsystem/atomic-reactor#228] opened 2015-07-16 15:28 UTC
Running on CentOS 7, I have a new build from upstream git in my [COPR](https://copr.fedoraproject.org/coprs/maxamillion/atomic-reactor/) installed:

```
[root@losbs ~]# cat /etc/centos-release
CentOS Linux release 7.1.1503 (Core) 
[root@losbs ~]# rpm -q atomic-reactor
atomic-reactor-1.4.0-1.git.0.599c689.el7.centos.noarch
```

And I built a new buildroot images with it just fine:

```
[root@losbs ~]# atomic-reactor create-build-image --reactor-tarball-path /usr/share/atomic-reactor/atomic-reactor.tar.gz /usr/share/atomic-reactor/images/dockerhost-builder/ buildroot                                                       
2015-07-16 10:17:03,723 - atomic_reactor.core - INFO - building image 'buildroot' from path '/tmp/tmpydbxzP/df-a47561c7-04d8-4308-9b76-48870047e1fd'
2015-07-16 10:17:03,744 - atomic_reactor.util - INFO - wait_for_command
2015-07-16 10:20:25,876 - atomic_reactor.util - INFO - no more logs
[root@losbs ~]# docker images
REPOSITORY                 TAG                 IMAGE ID            CREATED             VIRTUAL SIZE
buildroot                  latest              2371dabda515        6 minutes ago       470.1 MB
docker.io/fedora           latest              ded7cd95e059        7 weeks ago         186.5 MB
```

However when I attempt to do a build even using the exact example command, it fails:

```
[root@losbs ~]# atomic-reactor build git --method hostdocker --build-image buildroot --image test-image --uri "https://github.com/TomasTomecek/docker-hello-world.git"
2015-07-16 10:27:43,275 - atomic_reactor.outer - INFO - building image 'test-image'
2015-07-16 10:27:43,276 - atomic_reactor.core - INFO - building image 'buildroot' in container using docker from host
2015-07-16 10:27:43,276 - atomic_reactor.core - INFO - checking whether image 'buildroot' exists
2015-07-16 10:27:43,284 - atomic_reactor.core - INFO - creating container from image 'buildroot' and running it
2015-07-16 10:27:43,709 - atomic_reactor.core - INFO - getting stdout of container '8158e5f79bc81c58ecd3d726268a0af6e144efbd43f38332fdf686a49bb931f3'
2015-07-16 10:27:43,875 - atomic_reactor.util - INFO - wait_for_command
2015-07-16 10:27:44,499 - atomic_reactor.util - INFO - no more logs
2015-07-16 10:27:44,499 - atomic_reactor.core - INFO - waiting for container '8158e5f79bc81c58ecd3d726268a0af6e144efbd43f38332fdf686a49bb931f3' to finish
2015-07-16 10:27:44,650 - atomic_reactor.core - INFO - getting stdout of container '8158e5f79bc81c58ecd3d726268a0af6e144efbd43f38332fdf686a49bb931f3'
2015-07-16 10:27:44,656 - atomic_reactor - ERROR - build failed
[root@losbs ~]# docker ps -a
CONTAINER ID        IMAGE               COMMAND                CREATED             STATUS                     PORTS               NAMES
8158e5f79bc8        buildroot:latest    "atomic-reactor --ve   3 seconds ago       Exited (1) 2 seconds ago                       grave_payne
[root@losbs ~]# docker logs grave_payne
2015-07-16 15:27:43,874 - atomic_reactor.inner - DEBUG - getting build json from input path
2015-07-16 15:27:43,874 - atomic_reactor.plugin - DEBUG - loading plugins from dir '/usr/lib/python2.7/site-packages/atomic_reactor-1.3.7-py2.7.egg/atomic_reactor/plugins'
2015-07-16 15:27:43,874 - atomic_reactor.plugin - DEBUG - load file '/usr/lib/python2.7/site-packages/atomic_reactor-1.3.7-py2.7.egg/atomic_reactor/plugins/pre_return_dockerfile.py'
2015-07-16 15:27:43,875 - atomic_reactor.plugin - DEBUG - load file '/usr/lib/python2.7/site-packages/atomic_reactor-1.3.7-py2.7.egg/atomic_reactor/plugins/pre_inject_yum_repo.py'
2015-07-16 15:27:43,875 - atomic_reactor.plugin - DEBUG - load file '/usr/lib/python2.7/site-packages/atomic_reactor-1.3.7-py2.7.egg/atomic_reactor/plugins/pre_change_from_in_df.py'
2015-07-16 15:27:43,876 - atomic_reactor.plugin - DEBUG - load file '/usr/lib/python2.7/site-packages/atomic_reactor-1.3.7-py2.7.egg/atomic_reactor/plugins/input_path.py'
2015-07-16 15:27:43,876 - atomic_reactor.plugin - DEBUG - load file '/usr/lib/python2.7/site-packages/atomic_reactor-1.3.7-py2.7.egg/atomic_reactor/plugins/post_push_to_pulp.py'
2015-07-16 15:27:43,877 - atomic_reactor.plugin - WARNING - can't load module '/usr/lib/python2.7/site-packages/atomic_reactor-1.3.7-py2.7.egg/atomic_reactor/plugins/post_push_to_pulp.py': ImportError('No module named dockpulp',)
2015-07-16 15:27:43,877 - atomic_reactor.plugin - DEBUG - load file '/usr/lib/python2.7/site-packages/atomic_reactor-1.3.7-py2.7.egg/atomic_reactor/plugins/input_osv3.py'
2015-07-16 15:27:43,877 - atomic_reactor.plugin - DEBUG - load file '/usr/lib/python2.7/site-packages/atomic_reactor-1.3.7-py2.7.egg/atomic_reactor/plugins/post_cp_built_image_to_nfs.py'
2015-07-16 15:27:43,877 - atomic_reactor.plugin - DEBUG - load file '/usr/lib/python2.7/site-packages/atomic_reactor-1.3.7-py2.7.egg/atomic_reactor/plugins/pre_cp_dockerfile.py'
2015-07-16 15:27:43,878 - atomic_reactor.plugin - DEBUG - load file '/usr/lib/python2.7/site-packages/atomic_reactor-1.3.7-py2.7.egg/atomic_reactor/plugins/post_remove_built_image.py'
2015-07-16 15:27:43,878 - atomic_reactor.plugin - DEBUG - load file '/usr/lib/python2.7/site-packages/atomic_reactor-1.3.7-py2.7.egg/atomic_reactor/plugins/pre_add_yum_repo.py'
2015-07-16 15:27:43,878 - atomic_reactor.plugin - DEBUG - load file '/usr/lib/python2.7/site-packages/atomic_reactor-1.3.7-py2.7.egg/atomic_reactor/plugins/prepub_squash.py'
2015-07-16 15:27:43,879 - atomic_reactor.plugin - WARNING - can't load module '/usr/lib/python2.7/site-packages/atomic_reactor-1.3.7-py2.7.egg/atomic_reactor/plugins/prepub_squash.py': ImportError('No module named docker_scripts.squash',)
2015-07-16 15:27:43,879 - atomic_reactor.plugin - DEBUG - load file '/usr/lib/python2.7/site-packages/atomic_reactor-1.3.7-py2.7.egg/atomic_reactor/plugins/prepub_tests_for_image.py'
2015-07-16 15:27:43,879 - atomic_reactor.plugin - DEBUG - load file '/usr/lib/python2.7/site-packages/atomic_reactor-1.3.7-py2.7.egg/atomic_reactor/plugins/pre_pyrpkg_fetch_artefacts.py'
2015-07-16 15:27:43,880 - atomic_reactor.plugin - DEBUG - load file '/usr/lib/python2.7/site-packages/atomic_reactor-1.3.7-py2.7.egg/atomic_reactor/plugins/pre_add_labels_in_df.py'
2015-07-16 15:27:43,880 - atomic_reactor.plugin - DEBUG - load file '/usr/lib/python2.7/site-packages/atomic_reactor-1.3.7-py2.7.egg/atomic_reactor/plugins/pre_add_dockerfile.py'
2015-07-16 15:27:43,881 - atomic_reactor.plugin - DEBUG - load file '/usr/lib/python2.7/site-packages/atomic_reactor-1.3.7-py2.7.egg/atomic_reactor/plugins/pre_add_yum_repo_by_url.py'
2015-07-16 15:27:43,881 - atomic_reactor.plugin - DEBUG - load file '/usr/lib/python2.7/site-packages/atomic_reactor-1.3.7-py2.7.egg/atomic_reactor/plugins/pre_koji.py'
2015-07-16 15:27:44,423 - atomic_reactor.plugin - DEBUG - load file '/usr/lib/python2.7/site-packages/atomic_reactor-1.3.7-py2.7.egg/atomic_reactor/plugins/post_rpmqa.py'
2015-07-16 15:27:44,424 - atomic_reactor.plugin - DEBUG - load file '/usr/lib/python2.7/site-packages/atomic_reactor-1.3.7-py2.7.egg/atomic_reactor/plugins/post_store_logs_to_file.py'
2015-07-16 15:27:44,424 - atomic_reactor.plugin - DEBUG - load file '/usr/lib/python2.7/site-packages/atomic_reactor-1.3.7-py2.7.egg/atomic_reactor/plugins/pre_change_source_registry.py'
2015-07-16 15:27:44,424 - atomic_reactor.plugin - DEBUG - load file '/usr/lib/python2.7/site-packages/atomic_reactor-1.3.7-py2.7.egg/atomic_reactor/plugins/input_env.py'
2015-07-16 15:27:44,425 - atomic_reactor.plugin - DEBUG - load file '/usr/lib/python2.7/site-packages/atomic_reactor-1.3.7-py2.7.egg/atomic_reactor/plugins/post_tag_by_labels.py'
2015-07-16 15:27:44,425 - atomic_reactor.plugin - DEBUG - load file '/usr/lib/python2.7/site-packages/atomic_reactor-1.3.7-py2.7.egg/atomic_reactor/plugins/pre_assert_labels.py'
2015-07-16 15:27:44,425 - atomic_reactor.plugin - DEBUG - load file '/usr/lib/python2.7/site-packages/atomic_reactor-1.3.7-py2.7.egg/atomic_reactor/plugins/post_store_metadata_in_osv3.py'
2015-07-16 15:27:44,426 - atomic_reactor.plugin - WARNING - can't load module '/usr/lib/python2.7/site-packages/atomic_reactor-1.3.7-py2.7.egg/atomic_reactor/plugins/post_store_metadata_in_osv3.py': ImportError('No module named osbs.api',)
2015-07-16 15:27:44,426 - atomic_reactor.plugin - DEBUG - load file '/usr/lib/python2.7/site-packages/atomic_reactor-1.3.7-py2.7.egg/atomic_reactor/plugins/__init__.py'
2015-07-16 15:27:44,426 - atomic_reactor.plugin - DEBUG - load file '/usr/lib/python2.7/site-packages/atomic_reactor-1.3.7-py2.7.egg/atomic_reactor/plugins/post_tag_and_push.py'
2015-07-16 15:27:44,426 - atomic_reactor.plugin - DEBUG - running plugin 'path'
2015-07-16 15:27:44,427 - atomic_reactor.plugins.path - ERROR - couldn't read json from file '/run/share/build.json'
2015-07-16 15:27:44,427 - atomic_reactor.inner - DEBUG - build json: None
Traceback (most recent call last):
  File "/usr/bin/atomic-reactor", line 9, in <module>
    load_entry_point('atomic-reactor==1.3.7', 'console_scripts', 'atomic-reactor')()
  File "/usr/lib/python2.7/site-packages/atomic_reactor-1.3.7-py2.7.egg/atomic_reactor/cli/main.py", line 292, in run
    cli.run()
  File "/usr/lib/python2.7/site-packages/atomic_reactor-1.3.7-py2.7.egg/atomic_reactor/cli/main.py", line 275, in run
    args.func(args)
  File "/usr/lib/python2.7/site-packages/atomic_reactor-1.3.7-py2.7.egg/atomic_reactor/cli/main.py", line 89, in cli_inside_build
    build_inside(input=args.input, input_args=args.input_arg, substitutions=args.substitute)
  File "/usr/lib/python2.7/site-packages/atomic_reactor-1.3.7-py2.7.egg/atomic_reactor/inner.py", line 368, in build_inside
    raise RuntimeError("No valid build json!")
RuntimeError: No valid build json!
```

**Comment by maxamillion** [comment] 2015-07-20 15:27
This is related to SELinux Enforcing https://github.com/projectatomic/atomic-reactor/issues/206

**Comment by lcarva** [comment] 2021-03-25 12:53
This does not seem applicable anymore. Closing this issue. Feel free to reopen if the issue is still seen.

**Closed by lcarva** 2021-03-25 12:53 UTC
